### ISSUE TITLE
Docker image not available

### ISSUE THREAD

**Issue by sebastianroesch** [AmadeusITGroup/kanary#31]
When deploying Kanary using the Helm chart, it creates a deployment using the `kanary/operator:stable`, which does not exist in Docker.

What is the correct image name and label for Kanary?

**Comment by dbenque** [comment]
@sebastianroesch we have not yet pushed an image to a public repository. For now you need to build one locally:

make build && make TAG=latest container

I will update that ticket as soon as we release one on a public repo.
