### ISSUE TITLE
Please change the API group suffix

### ISSUE THREAD

**Issue by bgrant0607** [AmadeusITGroup/kanary#35]
Hi. `.k8s.io` is reserved for official Kubernetes subprojects. Please change `kanary.k8s.io` to `kanary.somethingelse`.

If you copied the `.k8s.io` pattern from some documentation or example in a Kubernetes repository, please point it out so that we can replace it with `example.com` or `example.org`.

Thanks.

@derekwaynecarr

**Comment by dbenque** [comment]
Ok, I will do that change. Thanks for your recommendation.

**Comment by bgrant0607** [comment]
Thanks much. I enjoyed the Kubecon talk.
