### ISSUE TITLE
kanary operatpr start error

### ISSUE THREAD

**Issue by hellolijj** [AmadeusITGroup/kanary#42]
```
[root@k8s-master kanary]# kubectl get pods
NAME                         READY   STATUS             RESTARTS   AGE
kanary-646fdc4545-585ls      0/1     CrashLoopBackOff   2          34s
nginx-dep-75bd58f5c7-76j6k   1/1     Running            0          10m
nginx-dep-75bd58f5c7-bdqb2   1/1     Running            0          10m
nginx-dep-75bd58f5c7-nxqbp   1/1     Running            0          10m
[root@k8s-master kanary]# kubectl logs kanary-646fdc4545-585ls
{"level":"info","ts":1563875916.5398905,"logger":"cmd","msg":"Go Version: go1.12.4"}
{"level":"info","ts":1563875916.5399652,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1563875916.539973,"logger":"cmd","msg":"operator-sdk Version: v0.3.0+git"}
{"level":"info","ts":1563875916.5509613,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1563875916.5867133,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1563875916.5867527,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1563875916.6060464,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1563875916.6062295,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"kanarydeployment-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1563875916.6062777,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"kanary.k8s.io","Kind":"KanaryDeployment"},"error":"no matches for kind \"KanaryDeployment\" in version \"kanary.k8s.io/v1alpha1\"","stacktrace":"github.com/amadeusitgroup/kanary/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/amadeusitgroup/kanary/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/amadeusitgroup/kanary/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/amadeusitgroup/kanary/pkg/controller/kanarydeployment.add\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/pkg/controller/kanarydeployment/kanarydeployment_controller.go:61\ngithub.com/amadeusitgroup/kanary/pkg/controller/kanarydeployment.Add\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/pkg/controller/kanarydeployment/kanarydeployment_controller.go:44\ngithub.com/amadeusitgroup/kanary/pkg/controller.AddToManager\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/pkg/controller/controller.go:13\nmain.main\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/cmd/manager/main.go:123\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}
{"level":"error","ts":1563875916.6063817,"logger":"cmd","msg":"","error":"no matches for kind \"KanaryDeployment\" in version \"kanary.k8s.io/v1alpha1\"","stacktrace":"github.com/amadeusitgroup/kanary/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/Users/cedric.lamoriniere/dev/perso/src/github.com/amadeusitgroup/kanary/cmd/manager/main.go:124\nruntime.main\n\t/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200"}
```

**Comment by dbenque** [comment]
Before running the operator and start injecting KanaryDeployment you must inject the definition of the CRD so that kubernetes know this new resource

```
kubectl apply -f deploy/crds/kanary_v1alpha1_kanarydeployment_crd.yaml
```

If you are running the example with nginx in the _example_ folder, there are couple of setup instructions that you can find in the readme file:
https://github.com/AmadeusITGroup/kanary/tree/master/examples/example

I will try to script it all like other examples. I the mean time can you please confirm that you can progress once the CRD is defined?

Regards, David

**Comment by hellolijj** [comment]
> Before running the operator and start injecting KanaryDeployment you must inject the definition of the CRD so that kubernetes know this new resource
> 
> ```
> kubectl apply -f deploy/crds/kanary_v1alpha1_kanarydeployment_crd.yaml
> ```
> 
> If you are running the example with nginx in the _example_ folder, there are couple of setup instructions that you can find in the readme file:
> https://github.com/AmadeusITGroup/kanary/tree/master/examples/example
> 
> I will try to script it all like other examples. I the mean time can you please confirm that you can progress once the CRD is defined?
> 
> Regards, David

thanks you reply, but i have installed `kanarydeployments` crd. 
```
[root@k8s-master kanary]# kubectl get crd
NAME                                         CREATED AT
kanarydeployments.kanary.k8s-operators.dev   2019-07-23T09:35:37Z
[root@k8s-master kanary]# kubectl apply -f deploy/crds/kanary_v1alpha1_kanarydeployment_crd.yaml
customresourcedefinition.apiextensions.k8s.io/kanarydeployments.kanary.k8s-operators.dev unchanged
[root@k8s-master kanary]#
```

**Comment by dbenque** [comment]
Ok, after a deep dive into your logs I noticed that the API Group is not correct:
Your operator is looking at **kanary.k8s.io** while the CRD has been moved to **kanary.k8s-operators.dev** following #35 

I think that the image version latest on dockerhub had not been updated after the fix for API Group suffix, so I am fixing it now. Please remove any local image that you may have in your environment:
```
docker rmi kanaryoperator / operator:latest
```
and change the image pull policy to always to be sure to force kubernetes to get the updated version in the operator.yaml file
```
imagePullPolicy: Always
```
Even better you can specify the image version v0.1 that I have just created in the operator.yaml file
```
      containers:
        - name: kanary
          image: kanaryoperator/operator:v0.1
```

If you have not used the image in Dockerhub, please update you local code to tag **v0.1** and rebuild the operator.

I hope this helps; I am waiting for your feedback, thanks.

**Comment by hellolijj** [comment]
> Ok, after a deep dive into your logs I noticed that the API Group is not correct:
> Your operator is looking at **kanary.k8s.io** while the CRD has been moved to **kanary.k8s-operators.dev** following #35
> 
> I think that the image version latest on dockerhub had not been updated after the fix for API Group suffix, so I am fixing it now. Please remove any local image that you may have in your environment:
> 
> ```
> docker rmi kanaryoperator / operator:latest
> ```
> 
> and change the image pull policy to always to be sure to force kubernetes to get the updated version in the operator.yaml file
> 
> ```
> imagePullPolicy: Always
> ```
> 
> Even better you can specify the image version v0.1 that I have just created in the operator.yaml file
> 
> ```
>       containers:
>         - name: kanary
>           image: kanaryoperator/operator:v0.1
> ```
> 
> If you have not used the image in Dockerhub, please update you local code to tag **v0.1** and rebuild the operator.
> 
> I hope this helps; I am waiting for your feedback, thanks.

thank you very much! I have  updated image and solve this problem.
