### ISSUE TITLE
Kanary resources are not cleaned automatically by the controller.

### ISSUE THREAD

**Issue by hellolijj** [AmadeusITGroup/kanary#43]
hi , i deploy kanary as docs

https://github.com/AmadeusITGroup/kanary/blob/master/examples/example/README.md#deploy-kanary-operator

but, i didn't get result as help docs, here is result:

```
[root@k8s-master kanary]# kubectl kanary get
  NAMESPACE  NAME       STATUS  DEPLOYMENT  SERVICE  SCALE   TRAFFIC  VALIDATION  DURATION
  default    nginx-dep  Failed  nginx-dep   nginx    static  both     manual      3m34.392132917s/1m0s
[root@k8s-master kanary]#
```

```
[root@k8s-master kanary]# kubectl get pods | grep nginx
nginx-dep-75bd58f5c7-8rf99                   1/1     Running   0          4m26s
nginx-dep-75bd58f5c7-8tswf                   1/1     Running   0          4m26s
nginx-dep-75bd58f5c7-lvx67                   1/1     Running   0          4m26s
nginx-dep-kanary-nginx-dep-8846f79f7-2vplj   1/1     Running   0          4m21s
[root@k8s-master kanary]# kubectl get svc | grep nginx
nginx                    ClusterIP   10.105.6.12     <none>        80/TCP              50m
nginx-kanary-nginx-dep   ClusterIP   10.109.32.46    <none>        80/TCP              4m30s
[root@k8s-master kanary]#
```

by the way, cloud you please show me where is `clean kanary resouce` codes?

**Comment by clamoriniere** [comment]
Hi @hellolijj 
It looks like the `kanary-controller` didn't succeed to create the "canary deployment" of the `nginx-dep` deployment: we can see that thanks to the `Failed` status. 
Could you print the full  `status` of the `KanaryDeployment` resource to have more information about the failure (`kubectl get kanary nginx-dep -o yaml`)?

about the cleaning. If you do `kubectl delete kanary nginx-dep`. it will delete the `KanaryDeployment` CustomResource and all associated resource. It works thanks to the `OwnerReference` Kubernetes resource mechanism. (https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents)

If you want to delete the `canary-controller` you can execute: `kubectl delete -f deploy/` then `kubectl delete -f deploy/crds`

**Comment by hellolijj** [comment]
@clamoriniere 
thank you for your clearly explanation, i have already find the reason of above case！
