### ISSUE TITLE
cann't pull image kanaryoperator/simpleserver

### ISSUE THREAD

**Issue by hellolijj** [AmadeusITGroup/kanary#44]
when i use istio to verificate kanary, i meet the ploblem as list:

```
  Type     Reason     Age                     From                 Message
  ----     ------     ----                    ----                 -------
  Normal   Scheduled  2m52s                   default-scheduler    Successfully assigned test/myapp-6b4fdcb4b8-bzsfn to k8s-master
  Normal   Pulled     2m50s                   kubelet, k8s-master  Container image "docker.io/istio/proxy_init:1.2.4" already present on machine
  Normal   Created    2m50s                   kubelet, k8s-master  Created container
  Normal   Started    2m50s                   kubelet, k8s-master  Started container
  Warning  Failed     2m45s                   kubelet, k8s-master  Failed to pull image "kanaryoperator/simpleserver:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for kanaryoperator/simpleserver, repository does not exist or may require 'docker login'
  Normal   Pulled     2m45s                   kubelet, k8s-master  Container image "docker.io/istio/proxyv2:1.2.4" already present on machine
  Normal   Created    2m45s                   kubelet, k8s-master  Created container
  Normal   Started    2m44s                   kubelet, k8s-master  Started container
  Normal   BackOff    2m42s (x2 over 2m43s)   kubelet, k8s-master  Back-off pulling image "kanaryoperator/simpleserver:latest"
  Warning  Failed     2m42s (x2 over 2m43s)   kubelet, k8s-master  Error: ImagePullBackOff
  Normal   Pulling    2m28s (x2 over 2m49s)   kubelet, k8s-master  pulling image "kanaryoperator/simpleserver:latest"
  Warning  Failed     2m25s (x2 over 2m45s)   kubelet, k8s-master  Error: ErrImagePull
  Warning  Unhealthy  2m25s (x10 over 2m43s)  kubelet, k8s-master  Readiness probe failed: HTTP probe failed with statuscode: 503
[root@k8s-master istio-1.2.4]# docker pull kanaryoperator/simpleserver:latest
Error response from daemon: pull access denied for kanaryoperator/simpleserver, repository does not exist or may require 'docker login'
```

so, could you please set image `kanaryoperator/simpleserver` as public ?

**Comment by Nexucis** [comment]
I guess you can't pull it because the image is not pushed in docker hub. And for what I saw in the repository, I believe that the image shall be built locally before using it

**Comment by dbenque** [comment]
The `simple-server` was never pushed as an image to dockerhub. It is used only in the exmaple/istio.

The script that runs the demo is using `KinD` https://github.com/kubernetes-sigs/kind to host and run the demo. As described in the `prerequesit` section in `demo.sh` https://github.com/AmadeusITGroup/kanary/blob/master/examples/istio-prom/demo.sh#L9 you should build the `simple-server` and push it to your KinD cluster. The is even `make` target to achieve that task as you can see in the linked line.

If you want tot run the demo somewhere else than KinD, and still use the `simple-server` you should build the `simple-server` with `make simple-server` and push the produced docker image to your docker registry.

If you think it really makes sense, I can also build it and push it to Dockerhub. Do you have usecases other than local demo and end to end tests?

**Comment by dbenque** [comment]
Finally I pushed it to dockerhub:
https://hub.docker.com/r/kanaryoperator/simpleserver/tags

It is not versioned. Just latest is being pushed since this is what is used in the demo. I hope it will help you.
